name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * SUN' # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update dependencies
        run: npm update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update dependencies"
          title: "chore: Automated dependency update"
          body: "This PR updates project dependencies to their latest versions."
          branch: "automated-dependency-updates"
